### ISSUE TITLE
Add aria2c to conda env

### ISSUE THREAD

**Issue by aozalevsky** [kalininalab/alphafold_non_docker#6]
As was pointed out in the [twitter](https://twitter.com/eugenevalkov/status/1422584012627869705) aria2c is a non-standard package, especially in HPC environments. Adding it in conda env and modifying the manual in a way, such as DB download would already be in the activated conda env might be a nice move.

**Comment by sanjaysrikakulam** [comment]
Hi @aozalevsky 

I will probably create a bash/python script that just uses wget and already existing system tools for downloading and extracting the data and I'll also add relevant documentation. Aria2c seem to require few dependencies and might need IT for that, also the bioconda version of it did not work because it still depends on OpenSSL 1.0.0 libs (not good).

**Comment by aozalevsky** [comment]
Good solution!

**Comment by sanjaysrikakulam** [comment]
Hi @aozalevsky 

I have added a DB download script to the repo and required documentation to the readme. I did not have the opportunity to test the script completely, but it should work. Along with this, reduced_dbs support is also now available for minimalistic runs.
